#ifndef XL_CAD_DEF_H__
#define XL_CAD_DEF_H__

namespace XL {
	enum class SHAPE_TYPE
	{
		POINT,
		LINE,
		RECTANGLE,
		CIRCLE,
		TRIANGLE,
		SPACE
	};

	enum class PROPERTY_ID
	{
		SHAPE = 0,
		// POINT
		PT_MODE,
		PT_COLOR,
		PT_RADIUS,
		PT_TOUCH_COUNT,
		PT_CUR_INDEX,
		PT_CUR_X,
		PT_CUR_Y,
		// RECTANGLE
		RECT_ID,
		RECT_Z_ORDER,
		RECT_LEFT,
		RECT_TOP,
		RECT_RIGHT,
		RECT_BOTTOM,
		RECT_BG_COLOR,
		RECT_TESS_LEVEL,
		RECT_BORDER_WIDTH_X,
		RECT_BORDER_WIDTH_Y,
		// CIRCLE
		CIRCLE_ID,
		CIRCLE_Z_ORDER,
		CIRCLE_CENTER_X,
		CIRCLE_CENTER_Y,
		CIRCLE_RADIUS_X,
		CIRCLE_RADIUS_Y,
		CIRCLE_BORDER_COLOR,
		CIRCLE_BORDER_WIDTH,
		CIRCLE_FILL,
		// LINE
		LINE_ID,
		LINE_Z_ORDER,
		LINE_START_X,
		LINE_START_Y,
		LINE_END_X,
		LINE_END_Y,
		LINE_WIDTH,
		LINE_COLOR,
		// TRIANGLE
		TRIANGLE_SIDE_A,
		TRIANGLE_SIDE_B,
		TRIANGLE_SIDE_C,
		TRIANGLE_COLOR,
		TRIANGLE_FILL,
	};
}

#endif // XL_CAD_DEF_H__